services:
  backend:
    image: node:18-alpine
    container_name: grup7_backend
    working_dir: /app
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    networks:
      - grup7_net
    environment:
      - DB_HOST=db
      - DB_USER=grup7_user
      - DB_PASSWORD=grup7_pass
      - DB_NAME=grup7
  frontend:
    image: node:18-alpine
    container_name: grup7_frontend
    working_dir: /app
    restart: unless-stopped
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    volumes:
      - ./frontend/client-joc:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - grup7_net
    environment:
      - VITE_SOCKET_URL=http://backend:8080
  db:
    image: mariadb:10.6
    container_name: grup7_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 'grup7_root_pass'
      MARIADB_DATABASE: 'grup7'
      MARIADB_USER: 'grup7_user'
      MARIADB_PASSWORD: 'grup7_pass'
    volumes:
      - ./docker_data/db:/var/lib/mysql
    networks:
      - grup7_net
networks:
  grup7_net:
    driver: bridge